apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
  namespace: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-demo-website
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50